### PR TITLE
Don't set OSProfile (Username/password) on images that use a Specialized Parent

### LINKED ISSUE #307: Creating an Image from an Azure Compute Gallery specialized image does not work
#### Overview of the Issue

I created a Citrix Cloud specialized image, with the 1.4.3 feature like this:

```
shared_image_gallery_replica_count = 5 #replicas per version
shared_image_gallery_timeout = "60m"
shared_gallery_image_version_exclude_from_latest = false

  shared_image_gallery_destination {
    subscription         = var.subscription_id
    resource_group       = "rg"
    gallery_name         = "images_sig"
    image_name           = "win001" #image definition
    image_version        = "23.6.14455"
    storage_account_type = "Standard_LRS"
    replication_regions  = ["eastus", "westus2"]
    specialized          = true
  }
```

#### Reproduction Steps

Then I try to create a new Image from the newly created image like this:

 ```
 shared_image_gallery {
    subscription       = var.subscription_id
    resource_group = "rg"
    gallery_name     = "images_sig"
    image_name      = "win001"
    image_version   = "23.6.14455"
  }

  shared_image_gallery_destination {
    subscription             = var.subscription_id
    resource_group       = "rg"
    gallery_name           = "mages_sig"
    image_name           = "win001" #image definition
    image_version        = "23.6.14456"
    storage_account_type = "Standard_LRS"
    replication_regions  = ["eastus", "westus2"]
    specialized             = true
  }
```
}

This error pops up when launching the VM:

`Build 'azure-arm.ppazwin001' errored after 7 minutes 3 seconds: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details." Details=[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"message\": \"Parameter 'osProfile' is not allowed.\",\r\n    \"target\": \"osProfile\"\r\n  }\r\n}"}]`

From Azure's troubleshooting page:
**ERROR**: Parameter 'osProfile' is not allowed

**CAUSE**: Admin username, password, or SSH keys were provided for a VM that was created from a specialized image version

**SOLUTION**: Don't include the admin username, password, or SSH keys if you intend to create a VM from that image. Otherwise, use a generalized image version and supply the admin username, password, or SSH keys

From the CLI, I am able to create a VM:
```
az vm create\
   --resource-group myRG  \
   --name 'myVM' \
   --image "/subscriptions/001/resourceGroups/rg/providers/Microsoft.Compute/galleries/images_sig/images/win001/versions/23.6.14455" \
   --specialized --admin-password ExampleWithMagic1!
```

### Plugin and Packer version

Packer v1.8.7
Azure RM v1.4.3

### Operating system and Environment details

MacOS Ventura 13.4

### Log Fragments and crash.log files

```
2023/06/14 11:41:51 ui: [1;32m==> azure-arm.ppazwin001: Deploying deployment template ...[0m
2023/06/14 11:41:51 ui: [1;32m==> azure-arm.ppazwin001:  -> ResourceGroupName : 'pkr-Resource-Group-uojx3vuyiv'[0m
2023/06/14 11:41:51 ui: [1;32m==> azure-arm.ppazwin001:  -> DeploymentName    : 'pkrdpuojx3vuyiv'[0m
2023/06/14 11:41:51 packer-plugin-azure_v1.4.3_x5.0_darwin_amd64 plugin: 2023/06/14 11:41:51 Azure request method="PUT" request="https://management.azure.com/subscriptions/9131afd8-4fbe-4b48-9680-723502256f82/resourcegroups/pkr-Resource-Group-uojx3vuyiv/providers/Microsoft.Resources/deployments/pkrdpuojx3vuyiv?api-version=2018-02-01" body="{\"properties\":{\"template\":{\"$schema\":\"http://schema.management.azure.com/schemas/2014-04-01-preview/deploymentTemplate.json\",\"contentVersion\":\"1.0.0.0\",\"parameters\":{\"adminPassword\":{\"type\":\"securestring\"},\"adminUsername\":{\"type\":\"string\"},\"commandToExecute\":{\"type\":\"string\"},\"dataDiskName\":{\"type\":\"string\"},\"dnsNameForPublicIP\":{\"type\":\"string\"},\"nicName\":{\"type\":\"string\"},\"nsgName\":{\"type\":\"string\"},\"osDiskName\":{\"type\":\"string\"},\"publicIPAddressName\":{\"type\":\"string\"},\"storageAccountBlobEndpoint\":{\"type\":\"string\"},\"subnetName\":{\"type\":\"string\"},\"virtualNetworkName\":{\"type\":\"string\"},\"vmName\":{\"type\":\"string\"},\"vmSize\":{\"type\":\"string\"}},\"resources\":[{\"apiVersion\":\"[variables('publicIPAddressApiVersion')]\",\"location\":\"[variables('location')]\",\"name\":\"[parameters('publicIPAddressName')]\",\"properties\":{\"dnsSettings\":{\"domainNameLabel\":\"[parameters('dnsNameForPublicIP')]\"},\"publicIPAllocationMethod\":\"[variables('publicIPAddressType')]\"},\"tags\":{\"ApplicationID\":\"PP001\",\"ApplicationName\":\"Virtual Desktop Infrastructure\",\"BusinessApplicationNumber\":\"PP001\",\"EnvironmentName\":\"Dev\"},\"type\":\"Microsoft.Network/publicIPAddresses\"},{\"apiVersion\":\"[variables('networkInterfacesApiVersion')]\",\"dependsOn\":[\"[concat('Microsoft.Network/publicIPAddresses/', parameters('publicIPAddressName'))]\"],\"location\":\"[variables('location')]\",\"name\":\"[parameters('nicName')]\",\"properties\":{\"ipConfigurations\":[{\"name\":\"ipconfig\",\"properties\":{\"privateIPAllocationMethod\":\"Dynamic\",\"publicIPAddress\":{\"id\":\"[resourceId('Microsoft.Network/publicIPAddresses', parameters('publicIPAddressName'))]\"},\"subnet\":{\"id\":\"[variables('subnetRef')]\"}}}]},\"tags\":{\"ApplicationID\":\"PP001\",\"ApplicationName\":\"Virtual Desktop Infrastructure\",\"BusinessApplicationNumber\":\"PP001\",\"EnvironmentName\":\"Dev\"},\"type\":\"Microsoft.Network/networkInterfaces\"},{\"apiVersion\":\"[variables('apiVersion')]\",\"dependsOn\":[\"[concat('Microsoft.Network/networkInterfaces/', parameters('nicName'))]\"],\"location\":\"[variables('location')]\",\"name\":\"[parameters('vmName')]\",\"properties\":{\"diagnosticsProfile\":{\"bootDiagnostics\":{\"enabled\":false}},\"hardwareProfile\":{\"vmSize\":\"[parameters('vmSize')]\"},\"networkProfile\":{\"networkInterfaces\":[{\"id\":\"[resourceId('Microsoft.Network/networkInterfaces', parameters('nicName'))]\"}]},\"osProfile\":{\"adminPassword\":\"[parameters('adminPassword')]\",\"adminUsername\":\"[parameters('adminUsername')]\",\"computerName\":\"[parameters('vmName')]\",\"secrets\":[{\"sourceVault\":{\"id\":\"[resourceId(resourceGroup().name, 'Microsoft.KeyVault/vaults', 'pkrkvuojx3vuyiv')]\"},\"vaultCertificates\":[{\"certificateStore\":\"My\",\"certificateUrl\":\"https://pkrkvuojx3vuyiv.vault.azure.net/secrets/packerKeyVaultSecret/06e6ec4ef7ce4b5189451523eafbf3ff\"}]}],\"windowsConfiguration\":{\"provisionVMAgent\":true,\"winRM\":{\"listeners\":[{\"certificateUrl\":\"https://pkrkvuojx3vuyiv.vault.azure.net/secrets/packerKeyVaultSecret/06e6ec4ef7ce4b5189451523eafbf3ff\",\"protocol\":\"https\"}]}}},\"storageProfile\":{\"imageReference\":{\"id\":\"/subscriptions/9131afd8-4fbe-4b48-9680-723502256f82/resourceGroups/paypal_rg/providers/Microsoft.Compute/galleries/paypal_images_sig/images/ppazwin001/versions/23.6.14455\"},\"osDisk\":{\"caching\":\"ReadWrite\",\"createOption\":\"FromImage\",\"name\":\"[parameters('osDiskName')]\",\"osType\":\"Windows\"}}},\"tags\":{\"ApplicationID\":\"PP001\",\"ApplicationName\":\"Virtual Desktop Infrastructure\",\"BusinessApplicationNumber\":\"PP001\",\"EnvironmentName\":\"Dev\"},\"type\":\"Microsoft.Compute/virtualMachines\"},{\"apiVersion\":\"2022-08-01\",\"condition\":\"[not(empty(parameters('commandToExecute')))]\",\"dependsOn\":[\"[resourceId('Microsoft.Compute/virtualMachines/', parameters('vmName'))]\"],\"location\":\"[variables('location')]\",\"name\":\"[concat(parameters('vmName'), '/extension-customscript')]\",\"properties\":{\"autoUpgradeMinorVersion\":true,\"publisher\":\"Microsoft.Compute\",\"settings\":{\"commandToExecute\":\"[parameters('commandToExecute')]\"},\"type\":\"CustomScriptExtension\",\"typeHandlerVersion\":\"1.8\"},\"tags\":{\"ApplicationID\":\"PP001\",\"ApplicationName\":\"Virtual Desktop Infrastructure\",\"BusinessApplicationNumber\":\"PP001\",\"EnvironmentName\":\"Dev\"},\"type\":\"Microsoft.Compute/virtualMachines/extensions\"}],\"variables\":{\"addressPrefix\":\"10.0.0.0/16\",\"apiVersion\":\"2018-06-01\",\"location\":\"[resourceGroup().location]\",\"managedDiskApiVersion\":\"2017-03-30\",\"networkInterfacesApiVersion\":\"2017-04-01\",\"networkSecurityGroupsApiVersion\":\"2019-04-01\",\"publicIPAddressApiVersion\":\"2017-04-01\",\"publicIPAddressType\":\"Dynamic\",\"sshKeyPath\":\"[concat('/home/',parameters('adminUsername'),'/.ssh/authorized_keys')]\",\"subnetAddressPrefix\":\"10.0.0.0/24\",\"subnetName\":\"default\",\"subnetRef\":\"[concat(variables('vnetID'),'/subnets/',variables('subnetName'))]\",\"virtualNetworkName\":\"packer-vnet\",\"virtualNetworkResourceGroup\":\"access_RG\",\"virtualNetworksApiVersion\":\"2017-04-01\",\"vmStorageAccountContainerName\":\"images\",\"vnetID\":\"[resourceId(variables('virtualNetworkResourceGroup'), 'Microsoft.Network/virtualNetworks', variables('virtualNetworkName'))]\"}},\"parameters\":{\"adminPassword\":{\"value\":\"SPz3a5OzS1Sjk3a9TZURFKMxwQvINha7\"},\"adminUsername\":{\"value\":\"packer\"},\"commandToExecute\":{\"value\":\"\"},\"dataDiskName\":{\"value\":\"pkrdduojx3vuyiv\"},\"dnsNameForPublicIP\":{\"value\":\"pkrvmuojx3vuyiv\"},\"nicName\":{\"value\":\"pkrniuojx3vuyiv\"},\"nsgName\":{\"value\":\"pkrsguojx3vuyiv\"},\"osDiskName\":{\"value\":\"pkrosuojx3vuyiv\"},\"publicIPAddressName\":{\"value\":\"pkripuojx3vuyiv\"},\"storageAccountBlobEndpoint\":{\"value\":\"\"},\"subnetName\":{\"value\":\"pkrsnuojx3vuyiv\"},\"virtualNetworkName\":{\"value\":\"pkrvnuojx3vuyiv\"},\"vmName\":{\"value\":\"pkrvmuojx3vuyiv\"},\"vmSize\":{\"value\":\"Standard_D4s_v4\"}},\"mode\":\"Incremental\"}}"
2023/06/14 11:41:52 packer-plugin-azure_v1.4.3_x5.0_darwin_amd64 plugin: 2023/06/14 11:41:52 Azure response status="201 Created" method="PUT" request="https://management.azure.com/subscriptions/9131afd8-4fbe-4b48-9680-723502256f82/resourcegroups/pkr-Resource-Group-uojx3vuyiv/providers/Microsoft.Resources/deployments/pkrdpuojx3vuyiv?api-version=2018-02-01" x-ms-request-id="f8baef03-9b9d-4c94-9b2d-bef842fc6caa" body="{\"id\":\"/subscriptions/9131afd8-4fbe-4b48-9680-723502256f82/resourceGroups/pkr-Resource-Group-uojx3vuyiv/providers/Microsoft.Resources/deployments/pkrdpuojx3vuyiv\",\"name\":\"pkrdpuojx3vuyiv\",\"properties\":{\"templateHash\":\"15584466449492202313\",\"parameters\":{\"adminPassword\":{\"type\":\"SecureString\"},\"adminUsername\":{\"type\":\"String\",\"value\":\"packer\"},\"commandToExecute\":{\"type\":\"String\",\"value\":\"\"},\"dataDiskName\":{\"type\":\"String\",\"value\":\"pkrdduojx3vuyiv\"},\"dnsNameForPublicIP\":{\"type\":\"String\",\"value\":\"pkrvmuojx3vuyiv\"},\"nicName\":{\"type\":\"String\",\"value\":\"pkrniuojx3vuyiv\"},\"nsgName\":{\"type\":\"String\",\"value\":\"pkrsguojx3vuyiv\"},\"osDiskName\":{\"type\":\"String\",\"value\":\"pkrosuojx3vuyiv\"},\"publicIPAddressName\":{\"type\":\"String\",\"value\":\"pkripuojx3vuyiv\"},\"storageAccountBlobEndpoint\":{\"type\":\"String\",\"value\":\"\"},\"subnetName\":{\"type\":\"String\",\"value\":\"pkrsnuojx3vuyiv\"},\"virtualNetworkName\":{\"type\":\"String\",\"value\":\"pkrvnuojx3vuyiv\"},\"vmName\":{\"type\":\"String\",\"value\":\"pkrvmuojx3vuyiv\"},\"vmSize\":{\"type\":\"String\",\"value\":\"Standard_D4s_v4\"}},\"mode\":\"Incremental\",\"provisioningState\":\"Accepted\",\"timestamp\":\"2023-06-14T15:41:52.7629896Z\",\"duration\":\"PT0.0007207S\",\"correlationId\":\"f8baef03-9b9d-4c94-9b2d-bef842fc6caa\",\"providers\":[{\"namespace\":\"Microsoft.Network\",\"resourceTypes\":[{\"resourceType\":\"publicIPAddresses\",\"locations\":[\"eastus\"]},{\"resourceType\":\"networkInterfaces\",\"locations\":[\"eastus\"]}]},{\"namespace\":\"Microsoft.Compute\",\"resourceTypes\":[{\"resourceType\":\"virtualMachines\",\"locations\":[\"eastus\"]}]}],\"dependencies\":[{\"dependsOn\":[{\"id\":\"/subscriptions/9131afd8-4fbe-4b48-9680-723502256f82/resourceGroups/pkr-Resource-Group-uojx3vuyiv/providers/Microsoft.Network/publicIPAddresses/pkripuojx3vuyiv\",\"resourceType\":\"Microsoft.Network/publicIPAddresses\",\"resourceName\":\"pkripuojx3vuyiv\"}],\"id\":\"/subscriptions/9131afd8-4fbe-4b48-9680-723502256f82/resourceGroups/pkr-Resource-Group-uojx3vuyiv/providers/Microsoft.Network/networkInterfaces/pkrniuojx3vuyiv\",\"resourceType\":\"Microsoft.Network/networkInterfaces\",\"resourceName\":\"pkrniuojx3vuyiv\"},{\"dependsOn\":[{\"id\":\"/subscriptions/9131afd8-4fbe-4b48-9680-723502256f82/resourceGroups/pkr-Resource-Group-uojx3vuyiv/providers/Microsoft.Network/networkInterfaces/pkrniuojx3vuyiv\",\"resourceType\":\"Microsoft.Network/networkInterfaces\",\"resourceName\":\"pkrniuojx3vuyiv\"}],\"id\":\"/subscriptions/9131afd8-4fbe-4b48-9680-723502256f82/resourceGroups/pkr-Resource-Group-uojx3vuyiv/providers/Microsoft.Compute/virtualMachines/pkrvmuojx3vuyiv\",\"resourceType\":\"Microsoft.Compute/virtualMachines\",\"resourceName\":\"pkrvmuojx3vuyiv\"},{\"dependsOn\":[{\"id\":\"/subscriptions/9131afd8-4fbe-4b48-9680-723502256f82/resourceGroups/pkr-Resource-Group-uojx3vuyiv/providers/Microsoft.Compute/virtualMachines/pkrvmuojx3vuyiv\",\"resourceType\":\"Microsoft.Compute/virtualMachines\",\"resourceName\":\"pkrvmuojx3vuyiv\"}],\"id\":\"/subscriptions/9131afd8-4fbe-4b48-9680-723502256f82/resourceGroups/pkr-Resource-Group-uojx3vuyiv/providers/Microsoft.Compute/virtualMachines/pkrvmuojx3vuyiv/extensions/extension-customscript\",\"resourceType\":\"Microsoft.Compute/virtualMachines/extensions\",\"resourceName\":\"pkrvmuojx3vuyiv/extension-customscript\"}]}}"
2023/06/14 11:41:52 packer-plugin-azure_v1.4.3_x5.0_darwin_amd64 plugin: 2023/06/14 11:41:52 Azure request method="GET" request="https://management.azure.com/subscriptions/9131afd8-4fbe-4b48-9680-723502256f82/resourcegroups/pkr-Resource-Group-uojx3vuyiv/providers/Microsoft.Resources/deployments/pkrdpuojx3vuyiv/operationStatuses/08585148495729958001?api-version=2018-02-01" body=""
2023/06/14 11:41:52 packer-plugin-azure_v1.4.3_x5.0_darwin_amd64 plugin: 2023/06/14 11:41:52 Azure response status="200 OK" method="GET" request="https://management.azure.com/subscriptions/9131afd8-4fbe-4b48-9680-723502256f82/resourcegroups/pkr-Resource-Group-uojx3vuyiv/providers/Microsoft.Resources/deployments/pkrdpuojx3vuyiv/operationStatuses/08585148495729958001?api-version=2018-02-01" x-ms-request-id="9311557f-3843-4af2-bc03-c19c158318b0" body="{\"status\":\"Running\"}"
2023/06/14 11:42:22 packer-plugin-azure_v1.4.3_x5.0_darwin_amd64 plugin: 2023/06/14 11:42:22 Azure request body="" method="GET" request="https://management.azure.com/subscriptions/9131afd8-4fbe-4b48-9680-723502256f82/resourcegroups/pkr-Resource-Group-uojx3vuyiv/providers/Microsoft.Resources/deployments/pkrdpuojx3vuyiv/operationStatuses/08585148495729958001?api-version=2018-02-01"
2023/06/14 11:42:22 packer-plugin-azure_v1.4.3_x5.0_darwin_amd64 plugin: 2023/06/14 11:42:22 Azure response x-ms-request-id="f89deeac-d601-4177-8034-dc98c12f6dcf" body="{\"status\":\"Failed\",\"error\":{\"code\":\"DeploymentFailed\",\"message\":\"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.\",\"details\":[{\"code\":\"BadRequest\",\"message\":\"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"InvalidParameter\\\",\\r\\n    \\\"message\\\": \\\"Parameter 'osProfile' is not allowed.\\\",\\r\\n    \\\"target\\\": \\\"osProfile\\\"\\r\\n  }\\r\\n}\"}]}}" status="200 OK" method="GET" request="https://management.azure.com/subscriptions/9131afd8-4fbe-4b48-9680-723502256f82/resourcegroups/pkr-Resource-Group-uojx3vuyiv/providers/Microsoft.Resources/deployments/pkrdpuojx3vuyiv/operationStatuses/08585148495729958001?api-version=2018-02-01"
2023/06/14 11:42:22 ui: [1;32m==> azure-arm.ppazwin001: ERROR: -> DeploymentFailed : At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.
==> azure-arm.ppazwin001: ERROR:   -> BadRequest
==> azure-arm.ppazwin001: ERROR:   -> InvalidParameter : Parameter 'osProfile' is not allowed.
==> azure-arm.ppazwin001:[0m
2023/06/14 11:42:22 ui error: [1;31m==> azure-arm.ppazwin001: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details." Details=[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"message\": \"Parameter 'osProfile' is not allowed.\",\r\n    \"target\": \"osProfile\"\r\n  }\r\n}"}][0m
2023/06/14 11:42:22 ui: [1;32m==> azure-arm.ppazwin001: 
==> azure-arm.ppazwin001: Deleting Virtual Machine deployment and its attatched resources...[0m

```

### PR DESCRIPTION
**Pull request by JenGoldstrich**
This PR fixes an issue added with plugin version v1.4.3

### Description 

In that plugin version we added support for creating a specialized ACG image with Packer, however when trying to use that specialized ACG image as a source for another image, we would incorrectly set the username and password, which is already defined in non-generalized VM Images.

### Changes

- Whenever a source SIG image is specialized, we remove the OS Profile field from the VM Deployment Template
- Added an acceptance test which requires an SSH PEM Private key file, the path of which is set under the environment variable `ARM_SSH_PRIVATE_KEY_FILE`
- ARM Acceptance tests no longer skip CLI auth tests, instead they fail the test file if Azure CLI auth is not set up

Closes #307

### CODE REVIEW

File: builder/azure/arm/builder_acc_test.go [hunk 1]
```diff
@@ -10,6 +10,8 @@ package arm
 // * ARM_CLIENT_SECRET
 // * ARM_SUBSCRIPTION_ID
 // * ARM_STORAGE_ACCOUNT
+// * AZURE_SSH_PASS - In our Linux SIG test we build two specialized images, this requires setting a shared password for both builds
+// * ARM_SSH_PRIVATE_KEY_LOCATION - the file location of a PEM encoded SSH private key,
```
Comment (lbajolet-hashicorp) [inline builder/azure/arm/builder_acc_test.go:14]: Is there a reason we want to use an external key and not one we generate on the fly?

File: builder/azure/arm/template_factory.go [hunk 2]
```diff
@@ -56,7 +56,41 @@ func GetKeyVaultDeployment(config *Config, secretValue string) (*resources.Deplo
 	return createDeploymentParameters(*doc, params)
 }
 
+func GetSpecializedVirtualMachineDeployment(config *Config) (*resources.Deployment, error) {
```
Comment (lbajolet-hashicorp) [inline builder/azure/arm/template_factory.go:59]: I wonder if we can use some config attribute to determine that we want a specialised VM deployment, and invoke that when relevant in `GetVirtualMachineDeployment`?

**Review by lbajolet-hashicorp — COMMENTED** [review]
Left a couple of questions regarding the implementation, but overall this looks good to me, I'll do another pass after you've reviewed my comments and addressed or discarded them

File: builder/azure/arm/template_factory.go (hunk 2 above)
Comment (JenGoldstrich) [reply builder/azure/arm/template_factory.go:59]: @lbajolet-hashicorp so the problem there is we don't pass in the config to GetVirtualMachineDeployment, and changing it was a bit of a messier change as its an interface used all over the place.

File: builder/azure/arm/builder_acc_test.go (hunk 1 above)
Comment (JenGoldstrich) [reply builder/azure/arm/builder_acc_test.go:14]: Only that I thought it would be simpler, certainly open to generating this on the fly, my plan was to just create and delete this key in CI when we start running acceptance tests there, I'll try to make this change!

File: builder/azure/arm/builder.go [hunk 3]
```diff
@@ -14,6 +14,7 @@ import (
 	"strings"
 	"time"
 
+	"github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2021-11-01/compute"
```
Comment (nywilken) [inline builder/azure/arm/builder.go:17]: Will there be any needed changes besides the import when switching to the HashiCorp Azure SDK?
 - If so it might help to port this change over once merged.

File: builder/azure/arm/builder_acc_test.go (hunk 1 above)
Comment (nywilken) [inline builder/azure/arm/builder_acc_test.go:14]: The location in the name is a little confusing to me. It is not clear to me if it is meant to be a file or directory on the remote or local filesystem.  It seems like this is just the path to a local SSH private key. Is that correct? 

If so what do you think about dropping Location from the name? 
```suggestion
// * ARM_SSH_PRIVATE_KEY_File - the file path of a local PEM encoded SSH private key to use in the test build,
```

File: builder/azure/arm/testdata/child_from_specialized_parent.pkr.hcl [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+    gallery_name   = "acctestgallery"
+    image_version  = "1.0.0"
+    resource_group = "packer-acceptance-test"
+  }
+  shared_image_gallery_destination {
+    image_name     = "arm-linux-specialized-sig"
+    gallery_name   = "acctestgallery"
+    image_version  = "1.0.1"
+    resource_group = "packer-acceptance-test"
+    specialized    = true
```
Comment (nywilken) [inline builder/azure/arm/testdata/child_from_specialized_parent.pkr.hcl:42]: Seeing as the parent image is specialized does the child honor the specialized property. In other words, if parent is specialized the child will be specialized? Or does the user have to explicitly set specialized to true?

File: builder/azure/common/template/template_builder.go [hunk 5]
```diff
@@ -517,6 +516,15 @@ func (s *TemplateBuilder) SetSecurityProfile(secureBootEnabled bool, vtpmEnabled
 	return nil
 }
 
+func (s *TemplateBuilder) SetSpecializedVM() error {
```
Comment (nywilken) [inline builder/azure/common/template/template_builder.go:519]: So my question around the child being specialized if the  parent is specialized stems from this function. It's name indicates that it is setting the vm as specialized but it is just removing the OsProfile settings. If this function will solely just clear the OsProfile what do you think about naming it differently. Maybe something like 
```suggestion
func (s *TemplateBuilder) ClearOsProfile() error {
```

File: builder/azure/common/template/template_builder.go [hunk 6]
```diff
@@ -517,6 +516,15 @@ func (s *TemplateBuilder) SetSecurityProfile(secureBootEnabled bool, vtpmEnabled
...
+	resource, err := s.getResourceByType(resourceVirtualMachine)
```
Comment (nywilken) [inline builder/azure/common/template/template_builder.go:520]: Do we need to validate the the virtualMachine has the specialized property set?

**Review by nywilken — COMMENTED** [review]
This is looking good. I left a few questions and a few suggestions on naming but otherwise it looks good.

File: builder/azure/arm/builder_acc_test.go (hunk 1 above)
Comment (nywilken) [reply builder/azure/arm/builder_acc_test.go:14]: I don't have an suggestions at this point but the requirements for env var in this test is a bit involved. Maybe AZURE_CLI_AUTH not being set should also be a Fatalf as it seems to be need for the new tests.

File: builder/azure/arm/template_factory.go (hunk 2 above)
Comment (lbajolet-hashicorp) [reply builder/azure/arm/template_factory.go:59]: Fair enough, if this is a messy change we can leave it as-is I would think.

File: builder/azure/arm/testdata/child_from_specialized_parent.pkr.hcl (hunk 4 above)
Comment (JenGoldstrich) [reply builder/azure/arm/testdata/child_from_specialized_parent.pkr.hcl:42]: The parent being specialized does not impact the child being specialized it just impacts the Virtual Machine you create.

You can create a specialized child or a generalized child from a specialized parent.

File: builder/azure/arm/builder_acc_test.go (hunk 1 above)
Comment (JenGoldstrich) [reply builder/azure/arm/builder_acc_test.go:14]: That's fine by me, I'd suggest KEY_FILE though, but I'll make that change

File: builder/azure/common/template/template_builder.go (hunk 5 above)
Comment (JenGoldstrich) [reply builder/azure/common/template/template_builder.go:519]: Sounds good to me, I'll make that change!

File: builder/azure/arm/builder_acc_test.go [hunk 7]
```diff
@@ -10,6 +10,8 @@ package arm
 // * ARM_CLIENT_SECRET
 // * ARM_SUBSCRIPTION_ID
 // * ARM_STORAGE_ACCOUNT
+// * AZURE_SSH_PASS - In our Linux SIG test we build two specialized images, this requires setting a shared password for both builds
```
Comment (nywilken) [inline builder/azure/arm/builder_acc_test.go:13]: I recommend adding a description to explain how this password is used.
```suggestion
// * ARM_SSH_PASS - In our Linux SIG test we build two specialized images (parent, child), which requires setting a shared password that can be used in both builds. The password is needed for .......
```

File: builder/azure/arm/builder_acc_test.go (hunk 1 above)
Comment (JenGoldstrich) [reply builder/azure/arm/builder_acc_test.go]: I agree with that, we should just require the environment variables, skipping them makes it easier to miss that tests aren't running

File: builder/azure/arm/builder_acc_test.go (hunk 7 above)
Comment (JenGoldstrich) [reply builder/azure/arm/builder_acc_test.go]: We actually didn't need it 😅, I've removed it

File: builder/azure/arm/testdata/child_from_specialized_parent.pkr.hcl (hunk 4 above)
Comment (nywilken) [reply builder/azure/arm/testdata/child_from_specialized_parent.pkr.hcl:35]: Got it thanks for the explanation

**Review by nywilken — APPROVED** [review]
Code wise this looks good go me. But I learned that I could only get the acceptance test to pass if I used an RSA key. I then found https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/ed25519-ssh-keys

Maybe that should be part of the description for the env var. Or call rename to `ARM_SSH_RSA_KEY_FILE`

File: builder/azure/arm/builder_acc_test.go (hunk 1 above)
Comment (JenGoldstrich) [reply builder/azure/arm/builder_acc_test.go]: Added that requirement to relevant tests
