### PR TITLE
[V2] Migrate all builders to hashicorp/go-azure-sdk 

### LINKED ISSUE #187: Improve the validation of image version
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description
I was recently building an azure-arm image using packer into a share image gallery and had given the value for image_version value as 'snapshot'. It rightly failed due to validation stating the follwoing error message
```
==> azure-arm.ofs-base-image: compute.GalleryImageVersionsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidParameter" Message="The image version name is invalid. The image version name should follow Major(int).Minor(int).Patch(int) format, where int is between 0 and 2,147,483,647 (inclusive). For e.g: 1.0.0, 2018.12.1 etc." Target="galleryImageVersionName"
```
While this behaviour is expected but the error appeared after the full process of provisining vm and running all the scripts and then while trying to apture an image. I think this is a bit too late considering the amount of time it takes to get to this error. I feel this should be validated in the early stages of `build`process or may be even as part of `validate` command
A written overview of the feature.
Introduce validation of image version as part of `validate` command or early stages `build` command
#### Use Case(s)

Any relevant use-cases that you see.
Any mistake in image version
#### Potential configuration

```
```

### LINKED ISSUE #235: support to add expiration date when setting winrm certificate in the KeyVault
When we enforce Azure policy on KeyVault that Secrets should have expiration dates set, following error happened.

azure-arm.azure: Setting the certificate in the KeyVault...
azure-arm.azure: Error setting winrm cert in custom keyvault: Failed to set secret to test/packerKeyVault, HTTP status code=403 (Forbidden)

### LINKED ISSUE #243: [Notice] V2 Azure Plugin - Changing SDKs
The version of the Azure SDK for Go the Packer Plugin relies on was deprecated in March https://azure.microsoft.com/en-us/updates/support-for-azure-sdk-libraries-that-do-not-conform-to-our-current-azure-sdk-guidelines-will-be-retired-as-of-31-march-2023/, to handle this deprecation we have decided to switch to the same SDK that the Terraform AzureRM Provider uses, github.com/hashicorp/go-azure-sdk.  This handles a lot of authentication logic for us and allows us to quickly add a lot of new highly requested features, like OIDC.   We plan to label this release as v2.0.0  .

The SDK change itself largely does not change what API endpoints we call during builds and as such should not require changes for most users, we currently have a beta release containing the changes only for the ARM Builder https://github.com/JenGoldstrich/packer-plugin-azure/releases/tag/v2.0.0-betarc1 which users may test if they are concerned about this breaking their workflows, this only contains the changes for the ARM builder, and not DevTestLabs and CHroot yet.  We are working on that next and will then release v2, the full list of current changes is available In the beta release notes, but it’s worth noting it is not the full list of changes in the v2 release.  

## Full List of current breaking changes  
1. We no longer connect to Storage Accounts via an account key but instead use a managed identity, as requested in hashicorp#250. As a consequence, the Teardown operation after a successful VHD build will fail unless the managed identity has permission to delete from the storage account. VHD builds will still succeed without this access, but they will leave an orphaned OS blob in their storage account.
2. Read Only SAS Uris that generated for VHD builds and managed image builds when sttting keep_os_disk to true, are no longer generated by default to mitigate security concerns. The Microsoft team does not recommend generating these SAS URIs as well.
3. Device Code authentication has been removed in favor of the recommend approach of using az login --use-device-code instead to replicate this functionality.

### LINKED ISSUE #250: Connect to Azure Storage account using Managed identity and not Account key.
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the [original issue](https://github.com/hashicorp/packer-plugin-azure/issues/250#issue-1451160212) to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

The Azure ARM VHD plugin for packer will try to use the account key instead of leveraging the Managed Identity of the VM/VMSS.
In the [azure_client.go](https://github.com/hashicorp/packer-plugin-azure/blob/main/builder/azure/arm/azure_client.go#L271) on row 279 is the definition of the Azure Storage Account connection using an account key.
There could be implemented a check to see if client id/secret is set or if another variable (use_azure_msi?) is set, to support true managed identity integration to interact with the storage account, thus excluding the need for Account keys/SAS tokens, and only allow Azure AD integration.

#### Use Case(s)

To allow "true" managed identity integration when trying to create a golden image and upload it as a VHD.
Microsoft recommendations are to disallow the use of Account keys.

#### Potential References

How to set the Managed identity using Azure SDK for go.
https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#DefaultAzureCredential

Example:

``` go 
func Example_client_NewClient() {
	// this example uses Azure Active Directory (AAD) to authenticate with Azure Blob Storage
	accountName, ok := os.LookupEnv("AZURE_STORAGE_ACCOUNT_NAME")
	if !ok {
		panic("AZURE_STORAGE_ACCOUNT_NAME could not be found")
	}
	serviceURL := fmt.Sprintf("https://%s.blob.core.windows.net/", accountName)

	// https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#DefaultAzureCredential
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	handleError(err)

	client, err := azblob.NewClient(serviceURL, cred, nil)
	handleError(err)

	fmt.Println(client.URL())
} 
```

### LINKED ISSUE #315: Failed to Delete Temporary VM Disk - Authentication Not Supported
_Originally posted by @JenGoldstrich in https://github.com/hashicorp/packer-plugin-azure/issues/190#issuecomment-1559761788_

I'm still seeing the same issue with the latest packer and azure plugins installed.

```
 packer --version
1.9.1
packer plugins installed
/home/ubm/.config/packer/plugins/github.com/hashicorp/azure/packer-plugin-azure_v1.4.3_x5.0_linux_amd64
```

```
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Deleting Virtual Machine deployment and its attatched resources...
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Adding to deletion queue -> Microsoft.Compute/virtualMachines : 'pkrvmzlbn4usnxl'
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Adding to deletion queue -> Microsoft.Network/networkInterfaces : 'pkrnizlbn4usnxl'
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Adding to deletion queue -> Microsoft.Network/publicIPAddresses : 'pkripzlbn4usnxl'
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Adding to deletion queue -> Microsoft.Network/virtualNetworks : 'pkrvnzlbn4usnxl'
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Attempting deletion -> Microsoft.Network/networkInterfaces : 'pkrnizlbn4usnxl'
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Attempting deletion -> Microsoft.Network/publicIPAddresses : 'pkripzlbn4usnxl'
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Attempting deletion -> Microsoft.Network/virtualNetworks : 'pkrvnzlbn4usnxl'
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Waiting for deletion of all resources...
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Attempting deletion -> Microsoft.Compute/virtualMachines : 'pkrvmzlbn4usnxl'
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Couldn't delete Microsoft.Network/publicIPAddresses resource. Will retry.
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Name: pkripzlbn4usnxl
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Couldn't delete Microsoft.Network/virtualNetworks resource. Will retry.
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Name: pkrvnzlbn4usnxl
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Couldn't delete Microsoft.Network/networkInterfaces resource. Will retry.
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Name: pkrnizlbn4usnxl
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Attempting deletion -> Microsoft.Network/publicIPAddresses : 'pkripzlbn4usnxl'
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Attempting deletion -> Microsoft.Network/virtualNetworks : 'pkrvnzlbn4usnxl'
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Attempting deletion -> Microsoft.Network/networkInterfaces : 'pkrnizlbn4usnxl'
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Couldn't delete Microsoft.Network/publicIPAddresses resource. Will retry.
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Name: pkripzlbn4usnxl
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Couldn't delete Microsoft.Network/virtualNetworks resource. Will retry.
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Name: pkrvnzlbn4usnxl
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Attempting deletion -> Microsoft.Network/publicIPAddresses : 'pkripzlbn4usnxl'
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Attempting deletion -> Microsoft.Network/virtualNetworks : 'pkrvnzlbn4usnxl'
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod:  Deleting -> Microsoft.Compute/disks : '/subscriptions/xxxxxxxxxxxxxxxxxxxx/providers/Microsoft.Compute/disks/pkroszlbn4usnxl'
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod:
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Error deleting resource.  Please delete manually.
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod:
==> linux.azure-arm.linux-ubuntu-2004-sig-image-prod: Name: /subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxx/providers/Microsoft.Compute/disks/pkroszlbn4usnxl
```

### PR DESCRIPTION
**Pull request by JenGoldstrich**
This PR combines several other PRs which remove the now deprecated "track 1" SDK we were using and switching over to the same SDK that the Terraform AzureRM provider uses https://github.com/hashicorp/go-azure-sdk

Removes VHD Deprecation warning

Removes `use_interactive_auth` from ARM/DTL builders, we recommend using the Azure CLI via `az login --use-device-code` and then using Azure CLI auth

adds `winrm_expiration_time` field to the ARM builder 

https://github.com/hashicorp/packer-plugin-azure/pull/306 - ARM Builder
https://github.com/JenGoldstrich/packer-plugin-azure/pull/4 - DTL Builder
https://github.com/JenGoldstrich/packer-plugin-azure/pull/5 - Chroot Builder
https://github.com/JenGoldstrich/packer-plugin-azure/pull/3 - Unwind template capture TODO
https://github.com/JenGoldstrich/packer-plugin-azure/pull/6 - Add Expiry Winrm Field, fail fast on in valid SIG version, and poll consistently as new SDK expects 

closes #243 
closes #250 
closes #235
closes #187
closes #315

### CODE REVIEW

File: builder/azure/arm/step_deploy_template.go [hunk 1]
```diff
@@ -112,13 +126,14 @@ func (s *StepDeployTemplate) Cleanup(state multistep.StateBag) {
 		}
 		if !state.Get(constants.ArmKeepOSDisk).(bool) {
 			ui.Say(fmt.Sprintf(" Deleting -> %s : '%s'", imageType, imageName))
-			err = s.deleteDisk(context.TODO(), imageName, resourceGroupName, isManagedDisk)
+			err = s.deleteDisk(ctx, imageName, resourceGroupName, (isManagedDisk || isSIGImage), subscriptionId, armStorageAccountName)
```
Comment (JenGoldstrich) [inline builder/azure/arm/step_deploy_template.go:129]: This is the change that fixes https://github.com/hashicorp/packer-plugin-azure/issues/315, since before SIG images would use the VHD deletion path

File: go.mod [hunk 2]
```diff
@@ -3,32 +3,32 @@ module github.com/hashicorp/packer-plugin-azure
...
+	github.com/Azure/go-autorest/autorest/date v0.3.0 // indirect
 	github.com/approvals/go-approval-tests v0.0.0-20210131072903-38d0b0ec12b1
-	github.com/dnaeon/go-vcr v1.1.0 // indirect
 	github.com/golang-jwt/jwt v3.2.2+incompatible
 	github.com/google/go-cmp v0.5.9
-	github.com/hashicorp/go-azure-helpers v0.16.5
+	github.com/hashicorp/go-azure-helpers v0.56.0
 	github.com/hashicorp/hcl/v2 v2.16.2
-	github.com/hashicorp/packer-plugin-sdk v0.5.1
+	github.com/hashicorp/packer-plugin-sdk v0.4.0
```
Comment (JenGoldstrich) [inline go.mod:14]: I had downgraded temporarily this please let me know what version I should upgrade this back to for the release!

File: go.mod [hunk 3]
```diff
@@ -3,32 +3,32 @@ module github.com/hashicorp/packer-plugin-azure
 go 1.19
 
 require (
-	github.com/Azure/azure-sdk-for-go v64.0.0+incompatible
```
Comment (JenGoldstrich) [inline go.mod:6]: 🎉

**Review by nywilken — COMMENTED** [review]
Jenna this is looking good already. Thank you a 💯 times for taking on this work and doing such a great job leading the effort. 

 I believe most of these changes have been reviewed from the previous PRs correct? 

I've slated time to go over the changes on Monday. To help with the review a bit could you rebase and squash the commits into logical PR merges? It would make it easy to cross reference.

**Comment by JenGoldstrich** [comment]
@nywilken done and done!

File: docs/builders/arm.mdx [hunk 4]
```diff
@@ -526,27 +526,6 @@ prevent running afoul of Azure decency controls.
 The password alphabet used for random values is
 **0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ**.
 
-### Deprecation Warning
```
Comment (JenGoldstrich) [inline docs/builders/arm.mdx:535]: Will post a longer clarification on the removal of the deprecation warning for VHDs in the release notes for v2.0.0

**Review by nywilken — COMMENTED** [review]
This is looking good. I have a few suggestions to help improve readability. I'm still working through a few more of the commits.

File: builder/azure/arm/step_capture_image.go [hunk 5]
```diff
@@ -70,6 +68,18 @@ func (s *StepCaptureImage) captureImage(ctx context.Context, vmId hashiVMSDK.Vir
 	return nil
 }
 
+func (s *StepCaptureImage) getVMID(ctx context.Context, vmId hashiVMSDK.VirtualMachineId) (string, error) {
+	vmResponse, err := s.client.VirtualMachinesClient.Get(ctx, vmId, hashiVMSDK.DefaultGetOperationOptions())
+	if err != nil {
+		return "", err
+	}
+	if vmResponse.Model != nil {
```
Comment (nywilken) [inline builder/azure/arm/step_capture_image.go:79]: What does it mean for vmResponse.Model to be nil? 

It doesn't seem like its an error and having an empty string is a valid response for this step. Is that correct? 

To make this a little more explicit I would suggest a small refactor
```
if vmResponse.Model == nil {
  // an empty VMID is value when ....
  return "", nil
}
vmId := vmResponse.Model.Properties.VMId
return *vmId, nil
```

File: builder/azure/arm/builder.go [hunk 6]
```diff
@@ -215,12 +231,15 @@ func (b *Builder) Run(ctx context.Context, ui packersdk.Ui, hook packersdk.Hook)
...
-		client.SubscriptionID = b.config.SharedGallery.Subscription
-		galleryImage, err := client.Get(ctx, b.config.SharedGallery.ResourceGroup, b.config.SharedGallery.GalleryName, b.config.SharedGallery.ImageName)
+		id := galleryimages.NewGalleryImageID(b.config.SharedGallery.Subscription, b.config.SharedGallery.ResourceGroup, b.config.SharedGallery.GalleryName, b.config.SharedGallery.ImageName)
+		galleryImage, err := client.Get(ctx, id)
 		if err != nil {
 			return nil, fmt.Errorf("the parent Shared Gallery Image '%s' from which to source the managed image version to does not exist in the resource group '%s' or does not contain managed image '%s'", b.config.SharedGallery.GalleryName, b.config.SharedGallery.ResourceGroup, b.config.SharedGallery.ImageName)
 		}
-		if galleryImage.OsState == compute.OperatingSystemStateTypesSpecialized {
+		if galleryImage.Model == nil {
+			return nil, fmt.Errorf("SDK returned empty model for gallery image")
```
[the remark this answers is not in the document]
Comment (JenGoldstrich) [reply builder/azure/arm/builder.go:240]: This is not an actionable error from us, tbh I just figured it was worth null checking it, I wouldn't expect the SDK to return a nill model without an error but I'll ask in their channel to clarify if that should be expected.  

If the SDK should never return it should we just remove these null checks, with the understanding that if the SDK behaves incorrectly we could reference a null pointer, what do you think?

File: builder/azure/arm/azure_client.go [hunk 7]
```diff
@@ -122,176 +79,169 @@ func errorCapture(client *AzureClient) autorest.RespondDecorator {
...
 	return func(r autorest.Responder) autorest.Responder {
 		return autorest.DecorateResponder(r, decorators...)
 	}
 }
 
-func NewAzureClient(subscriptionID, sigSubscriptionID, resourceGroupName, storageAccountName string,
-	cloud *azure.Environment, sharedGalleryTimeout time.Duration, pollingDuration time.Duration,
-	servicePrincipalToken, servicePrincipalTokenVault *adal.ServicePrincipalToken) (*AzureClient, error) {
+// Returns an Azure Client used for the Azure Resource Manager
+// Also returns the Azure object ID for the authentication method used in the build
```
[the remark this answers is not in the document]
Comment (JenGoldstrich) [reply builder/azure/arm/azure_client.go:102]: Storing the ObjectID in the Client makes sense to me, this object ID is the user ID basically, it is associated with the user's Azure service principal, it is required for Windows builds only though.

I will implement your change and try and clear this up in the comments, thanks for the feedback!

File: builder/azure/arm/builder.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (JenGoldstrich) [reply builder/azure/arm/builder.go:240]: To update that the TF Provider does null check the Model, so I think we should as well, maybe we can refine this error?

File: builder/azure/arm/step_capture_image.go (hunk 5 above)
Comment (JenGoldstrich) [reply builder/azure/arm/step_capture_image.go:79]: Good call, I think I just wrote this wrong tbh if the Model is nil we just need to error here with the same error we do everywhere

File: builder/azure/arm/azure_client.go [hunk 8]
```diff
@@ -122,176 +79,169 @@ func errorCapture(client *AzureClient) autorest.RespondDecorator {
 	}
 }
 
-// WAITING(chrboum): I have logged https://github.com/Azure/azure-sdk-for-go/issues/311 to get this
-// method included in the SDK.  It has been accepted, and I'll cut over to the official way
-// once it ships.
+func errorCaptureTrack2(client *AzureClient) client.ResponseMiddleware {
```
[the remark this answers is not in the document]
Comment (JenGoldstrich) [reply builder/azure/arm/azure_client.go:82]: For sure, one thing I'd like to clarify is that the above waiting error was on "byConcatDecorators", and not on the errorCapture method, the error Capture method just formats the error in a way we expect when one happens, and logs it. by concat decorators basicaly combined two pieces of response middlewares into one, due to limitations in autorest.  The new SDK allows us to have a list of request/response middleware functions so this is not needed in track 2

File: builder/azure/arm/azure_client.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (JenGoldstrich) [reply builder/azure/arm/azure_client.go]: Implemented in newest commit

File: builder/azure/arm/builder.go [hunk 9]
```diff
@@ -81,28 +78,34 @@ func (b *Builder) Run(ctx context.Context, ui packersdk.Ui, hook packersdk.Hook)
...
 
 	ui.Message("Creating Azure Resource Manager (ARM) client ...")
-	azureClient, err := NewAzureClient(
-		b.config.ClientConfig.SubscriptionID,
-		b.config.SharedGalleryDestination.SigDestinationSubscription,
-		b.config.ResourceGroupName,
-		b.config.StorageAccount,
+	azureClient, objectID, err := NewAzureClient(
+		ctx,
+		(b.config.ResourceGroupName != "" || b.config.StorageAccount != ""),
```
[the remark this answers is not in the document]
Comment (JenGoldstrich) [reply builder/azure/arm/builder.go]: Implemented in newest commit Implemented in newest commit

File: builder/azure/arm/step_capture_image.go (hunk 5 above)
Comment (JenGoldstrich) [reply builder/azure/arm/step_capture_image.go:80]: Implemented this in new commit, not counting the general SDK error, but the Model being nill here IMO should just throw an error, if we can't Get the VM here we won't be able to capture it later on anyways

File: builder/azure/arm/builder.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (JenGoldstrich) [reply builder/azure/arm/builder.go]: Chatted with this offline and we talked through this and decided on a common error to throw for this case, implemented in newest commit

File: builder/azure/arm/step_capture_image.go [hunk 10]
```diff
@@ -40,58 +40,79 @@ func NewStepCaptureImage(client *AzureClient, ui packersdk.Ui) *StepCaptureImage
...
+	vmResponse, err := s.client.VirtualMachinesClient.Get(ctx, vmId, virtualmachines.DefaultGetOperationOptions())
+	if err != nil {
+		return "", err
 	}
-	return f.WaitForCompletionRef(ctx, s.client.VirtualMachinesClient.Client)
+	if vmResponse.Model != nil {
+		vmId := vmResponse.Model.Properties.VMId
+		return *vmId, nil
+	}
+	return "", errors.New(client.SDK_NULL_MODEL_ERROR)
```
Comment (nywilken) [inline builder/azure/arm/step_capture_image.go:85]: Instead of creating a constant string to include as the error message. Have you considered creating a custom Error type that can be returned here? 

```go
return "", client.NullModelSDKErr
```

nit: We generally use Camel casing for snake casing for constants and variable names.

File: builder/azure/dtl/template_factory.go [hunk 11]
```diff
@@ -62,51 +62,50 @@ func GetVirtualMachineDeployment(config *Config) (*dtl.LabVirtualMachineCreation
...
+		Artifacts:   &dtlArtifacts,
 	}
 
-	labMachine := &dtl.LabVirtualMachineCreationParameter{
+	labMachine := &hashiDTLLabsSDK.LabVirtualMachineCreationParameter{
 		Name:     &config.tmpComputeName,
 		Location: &config.Location,
-		Tags:     config.AzureTags,
-		LabVirtualMachineCreationParameterProperties: labMachineProps,
+		// TODO
```
[the remark this answers is not in the document]
Comment (JenGoldstrich) [reply builder/azure/dtl/template_factory.go]: Nope! Should be fixed in the newest commit though I believe I had already addressed this one

File: builder/azure/arm/step_capture_image.go (hunk 10 above)
Comment (JenGoldstrich) [reply builder/azure/arm/step_capture_image.go]: I originally chose a string cause errors can't be constantly defined, it makes sense imo to just make it a var though so it can be a custom Error, and I've also renamed it with your suggested name in newest commit

File: builder/azure/arm/artifact.go [hunk 12]
```diff
@@ -115,80 +92,33 @@ func NewSharedImageArtifact(osType, destinationSharedImageGalleryId string, loca
...
-func NewArtifact(template *CaptureTemplate, getSasUrl func(name string) string, osType string, generatedData map[string]interface{}) (*Artifact, error) {
-	if template == nil {
-		return nil, fmt.Errorf("nil capture template")
-	}
-
-	if len(template.Resources) != 1 {
-		return nil, fmt.Errorf("malformed capture template, expected one resource")
-	}
+func NewArtifact(vmInternalID string, storageAccountUrl string, storageAccountLocation string, osType string, additionalDiskCount int, generatedData map[string]interface{}) (*Artifact, error) {
+	vhdUri := fmt.Sprintf("%ssystem/Microsoft.Compute/Images/images/packer-osDisk.%s.vhd", storageAccountUrl, vmInternalID)
```
[the remark this answers is not in the document]
Comment (nywilken) [reply builder/azure/arm/artifact.go:96]: Just to close the loop - as we discuss internally we will hold on refactors to not introduce untested changes.

**Review by nywilken — APPROVED** [review]
Nicely done. Please use the upgrade notes sections once released to communicate major breaking changes and migration steps for folks using v1 of the plugin.

File: builder/azure/common/client/config.go [hunk 13]
```diff
@@ -224,9 +217,9 @@ func (c Config) Validate(errs *packersdk.MultiError) {
 		if err != nil {
 			errs = packersdk.MultiErrorAppend(errs, fmt.Errorf("client_jwt is not a JWT: %v", err))
 		} else {
-			if claims.ExpiresAt < time.Now().Add(5*time.Minute).Unix() {
-				errs = packersdk.MultiErrorAppend(errs, fmt.Errorf("client_jwt will expire within 5 minutes, please use a JWT that is valid for at least 5 minutes"))
-			}
+			//if claims.ExpiresAt < time.Now().Add(5*time.Minute).Unix() {
+			//	errs = packersdk.MultiErrorAppend(errs, fmt.Errorf("%d %d, client_jwt will expire within 5 minutes, please use a JWT that is valid for at least 5 minutes", claims.ExpiresAt, time.Now().Add(5*time.Minute).Unix()))
+			//}
```
Comment (lbajolet-hashicorp) [inline builder/azure/common/client/config.go:222]: Is there a reason why this gets commented and not removed?

**Review by lbajolet-hashicorp — APPROVED** [review]
Left a few nits, but overall this looks good @JenGoldstrich! Good job on that

File: builder/azure/common/client/config.go (hunk 13 above)
Comment (JenGoldstrich) [reply builder/azure/common/client/config.go:222]: Good catch Lucas! This check should be removed as it prevents OIDC authentication, I had commented it out earlier while testing OIDC and forgot to remove it, I'll do so

File: builder/azure/arm/config.go [hunk 14]
```diff
@@ -1239,6 +1245,11 @@ func assertRequiredParametersSet(c *Config, errs *packersdk.MultiError) {
 		}
 		if c.SharedGalleryDestination.SigDestinationImageVersion == "" {
 			errs = packersdk.MultiErrorAppend(errs, fmt.Errorf("An image_version must be specified for shared_image_gallery_destination"))
```
[the remark this answers is not in the document]
Comment (JenGoldstrich) [reply builder/azure/arm/config.go:1247]: Great point, I will make that change
