### PR TITLE
fix: Delete Conflicting Gallery Image Versions when force flag is set

### LINKED ISSUE #392: The -force option it not cleaning up the gallery image
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

When using the `-force` option to packer and creating a new image in the image gallery it fails to remove the image from the gallery.

##### Build the image the first time

```shell
$ packer build .
Linux.azure-arm.template: output will be in this color.

==> Linux.azure-arm.template: Running builder ...
    Linux.azure-arm.template: Creating Azure Resource Manager (ARM) client ...
==> Linux.azure-arm.template: Getting source image id for the deployment ...
==> Linux.azure-arm.template:  -> SourceImageName: '/subscriptions/88888888-4444-4444-4444-cccccccccccc/resourceGroups/rg-ede-sig/providers/Microsoft.Compute/images/initial_CentOS7.9_Core_x64_2024.02.16'
==> Linux.azure-arm.template: Using existing resource group ...
==> Linux.azure-arm.template:  -> ResourceGroupName : 'rg-ede-default'
==> Linux.azure-arm.template:  -> Location          : 'centralus'
==> Linux.azure-arm.template: Validating deployment template ...
==> Linux.azure-arm.template:  -> ResourceGroupName : 'rg-ede-default'
==> Linux.azure-arm.template:  -> DeploymentName    : 'pkrdp4tee6jjg8s'
==> Linux.azure-arm.template: Deploying deployment template ...
==> Linux.azure-arm.template:  -> ResourceGroupName : 'rg-ede-default'
==> Linux.azure-arm.template:  -> DeploymentName    : 'pkrdp4tee6jjg8s'
==> Linux.azure-arm.template: Getting the VM's IP address ...
==> Linux.azure-arm.template:  -> ResourceGroupName   : 'rg-ede-default'
==> Linux.azure-arm.template:  -> PublicIPAddressName : 'pkrip4tee6jjg8s'
==> Linux.azure-arm.template:  -> NicName             : 'pkrni4tee6jjg8s'
==> Linux.azure-arm.template:  -> Network Connection  : 'PrivateEndpoint'
==> Linux.azure-arm.template:  -> IP Address          : '10.18.0.133'
==> Linux.azure-arm.template: Waiting for SSH to become available...
==> Linux.azure-arm.template: Connected to SSH!
==> Linux.azure-arm.template: Querying the machine's properties ...
==> Linux.azure-arm.template:  -> ResourceGroupName : 'rg-ede-default'
==> Linux.azure-arm.template:  -> ComputeName       : 'pkrvm4tee6jjg8s'
==> Linux.azure-arm.template:  -> Managed OS Disk   : '/subscriptions/88888888-4444-4444-4444-cccccccccccc/resourceGroups/rg-ede-default/providers/Microsoft.Compute/disks/pkros4tee6jjg8s'
==> Linux.azure-arm.template: Querying the machine's additional disks properties ...
==> Linux.azure-arm.template:  -> ResourceGroupName : 'rg-ede-default'
==> Linux.azure-arm.template:  -> ComputeName       : 'pkrvm4tee6jjg8s'
==> Linux.azure-arm.template: Powering off machine ...
==> Linux.azure-arm.template:  -> ResourceGroupName : 'rg-ede-default'
==> Linux.azure-arm.template:  -> ComputeName       : 'pkrvm4tee6jjg8s'
==> Linux.azure-arm.template:  -> Compute ResourceGroupName : 'rg-ede-default'
==> Linux.azure-arm.template:  -> Compute Name              : 'pkrvm4tee6jjg8s'
==> Linux.azure-arm.template:  -> Compute Location          : 'centralus'
==> Linux.azure-arm.template: Generalizing machine ...
==> Linux.azure-arm.template: Capturing image ...
==> Linux.azure-arm.template:  -> Image ResourceGroupName   : 'rg-ede-sig'
==> Linux.azure-arm.template:  -> Image Name                : 'basic_CentOS7.9_Core_x64_0.0.1'
==> Linux.azure-arm.template:  -> Image Location            : 'centralus'
==> Linux.azure-arm.template: Publishing to Shared Image Gallery ...
==> Linux.azure-arm.template:  -> Source ID used for SIG publish        : '/subscriptions/88888888-4444-4444-4444-cccccccccccc/resourceGroups/rg-ede-sig/providers/Microsoft.Compute/images/basic_CentOS7.9_Core_x64_0.0.1'
==> Linux.azure-arm.template:  -> SIG publish resource group            : 'rg-ede-sig'
==> Linux.azure-arm.template:  -> SIG gallery name                      : 'sig0098centralus'
==> Linux.azure-arm.template:  -> SIG image name                        : 'basic_CentOS7.9_Core_x64'
==> Linux.azure-arm.template:  -> SIG image version                     : '0.0.1'
==> Linux.azure-arm.template:  -> SIG replication regions               : '[centralus]'
==> Linux.azure-arm.template:  -> SIG storage account type              : ''
==> Linux.azure-arm.template:  -> SIG image version endoflife date      : ''
==> Linux.azure-arm.template:  -> SIG image version exclude from latest : 'false'
==> Linux.azure-arm.template:  -> SIG replica count [1, 100]            : '1'
==> Linux.azure-arm.template:  -> Shared Gallery Image Version ID : '/subscriptions/88888888-4444-4444-4444-cccccccccccc/resourceGroups/rg-ede-sig/providers/Microsoft.Compute/galleries/sig0098centralus/images/basic_CentOS7.9_Core_x64/versions/0.0.1'
==> Linux.azure-arm.template: 
==> Linux.azure-arm.template: Deleting Virtual Machine deployment and its attatched resources...
==> Linux.azure-arm.template: Adding to deletion queue -> Microsoft.Compute/virtualMachines : 'pkrvm4tee6jjg8s'
==> Linux.azure-arm.template: Adding to deletion queue -> Microsoft.Network/networkInterfaces : 'pkrni4tee6jjg8s'
==> Linux.azure-arm.template: Waiting for deletion of all resources...
==> Linux.azure-arm.template: Attempting deletion -> Microsoft.Network/networkInterfaces : 'pkrni4tee6jjg8s'
==> Linux.azure-arm.template: Attempting deletion -> Microsoft.Compute/virtualMachines : 'pkrvm4tee6jjg8s'
==> Linux.azure-arm.template: Couldn't delete Microsoft.Network/networkInterfaces resource. Will retry.
==> Linux.azure-arm.template: Name: pkrni4tee6jjg8s
==> Linux.azure-arm.template: Attempting deletion -> Microsoft.Network/networkInterfaces : 'pkrni4tee6jjg8s'
==> Linux.azure-arm.template:  Deleting -> Microsoft.Compute/disks : '/subscriptions/88888888-4444-4444-4444-ccccccccccccresourceGroups/rg-ede-default/providers/Microsoft.Compute/disks/pkros4tee6jjg8s'
==> Linux.azure-arm.template: Removing the created Deployment object: 'pkrdp4tee6jjg8s'
==> Linux.azure-arm.template: 
==> Linux.azure-arm.template: The resource group was not created by Packer, not deleting ...
Build 'Linux.azure-arm.template' finished after 13 minutes 16 seconds.

==> Wait completed after 13 minutes 16 seconds

==> Builds finished. The artifacts of successful builds are:
--> Linux.azure-arm.template: Azure.ResourceManagement.VMImage:

OSType: Linux
ManagedImageResourceGroupName: rg-ede-sig
ManagedImageName: basic_CentOS7.9_Core_x64_0.0.1
ManagedImageId: /subscriptions/88888888-4444-4444-4444-cccccccccccc/resourceGroups/rg-ede-sig/providers/Microsoft.Compute/images/basic_CentOS7.9_Core_x64_0.0.1
ManagedImageLocation: centralus
ManagedImageSharedImageGalleryId: /subscriptions/88888888-4444-4444-4444-cccccccccccc/resourceGroups/rg-ede-sig/providers/Microsoft.Compute/galleries/sig0098centralus/images/basic_CentOS7.9_Core_x64/versions/0.0.1
SharedImageGalleryResourceGroup: rg-ede-sig
SharedImageGalleryName: sig0098centralus
SharedImageGalleryImageName: basic_CentOS7.9_Core_x64
SharedImageGalleryImageVersion: 0.0.1
SharedImageGalleryReplicatedRegions: centralus
```

##### Rebuild the image a second time (iterate on the template config)

```shell
$ packer build -force . 
Linux.azure-arm.template: output will be in this color.

==> Linux.azure-arm.template: Running builder ...
    Linux.azure-arm.template: Creating Azure Resource Manager (ARM) client ...
==> Linux.azure-arm.template: the managed image named basic_CentOS7.9_Core_x64_0.0.1 already exists, but deleting it due to -force flag
Build 'Linux.azure-arm.template' errored after 31 seconds 239 milliseconds: a gallery image version for image name:version basic_CentOS7.9_Core_x64:0.0.1 already exists in gallery sig0098centralus

==> Wait completed after 31 seconds 240 milliseconds

==> Some builds didn't complete successfully and had errors:
--> Linux.azure-arm.template: a gallery image version for image name:version basic_CentOS7.9_Core_x64:0.0.1 already exists in gallery sig0098centralus

==> Builds finished but no artifacts were created.
```

### Plugin and Packer version

From `packer version`

```shell
$ packer version
Packer v1.10.2
```

#### `source-azure.pkr.hcl`

```hcl
source "azure-arm" "template" {
    subscription_id           = var.subscription_id
    client_id                 = var.client_id
    client_cert_path          = var.client_cert_path
    client_cert_password      = var.client_cert_pass
    polling_duration_timeout  = "30m"

    azure_tags = var.az_tags

    os_type                   ="Linux"
    os_disk_size_gb           = 50

    shared_image_gallery {
        subscription   = var.subscription_id
        resource_group = var.az_shared_library_rg
        gallery_name   = var.az_gallery_name
        image_name     = var.src_image_name
        image_version  = var.az_src_image_version
    }

    shared_image_gallery_destination {
        subscription        = var.subscription_id
        resource_group      = var.az_shared_library_rg
        gallery_name        = var.az_gallery_name
        image_name          = var.vm_prefix
        image_version       = "0.0.1"
        replication_regions = var.az_replication_regions
    }

    shared_image_gallery_timeout           = "1h"
    managed_image_name                     = "${var.vm_prefix}_0.0.1"
    managed_image_resource_group_name      = var.az_shared_library_rg
    vm_size                                = "Standard_D2_v4"
    private_virtual_network_with_public_ip = false
    virtual_network_name                   = var.az_vnet_name
    virtual_network_subnet_name            = var.az_subnet_name
    virtual_network_resource_group_name    = var.az_subnet_rg
    build_resource_group_name              = var.az_build_rg

    // Settings for the communicator
    communicator   = "ssh"
    ssh_username   = var.vm_usr
    ssh_password   = var.vm_psw
  }
```

#### `vars.pkr.hcl`

```hcl
variable "subscription_id" {
    type = string
}

variable "client_id" {
    type = string
}

variable "client_cert_path" {
    type = string
}

variable "client_cert_pass" {
    type = string
}

variable "az_tags" {
  type        = map(string)
  description = "Tags assigned to created resources. (Optional for: base and baked)"
  default     = {
    edaas_purpose     = "Test azure builder 2.0.4"
    edaas_environment = "QA"
    edaas_user_email  = "email@someplace.com"
  }
}

variable "az_shared_library_rg" {
  type        = string
}

variable "az_gallery_name" {
  type        = string
}

variable "src_image_name" {
  type        = string
}

variable "az_src_image_version" {
  type        = string
}

variable "vm_prefix" {
  type        = string
}

variable "az_replication_regions" {
  type        = list(string)
}

variable "az_vnet_name" {
  type        = string
}

variable "az_subnet_rg" {
  type        = string
}

variable "az_build_rg" {
  type        = string
}

variable "az_subnet_name" {
  type        = string
}

variable "vm_psw" {
  type        = string
}

variable "vm_usr" {
  type        = string
}
```

#### `versions.pkr.hcl`

```hcl
packer {
  required_plugins {
    azure = {
      version = "2.0.4"
      source  = "github.com/hashicorp/azure"
    }
  }
}

```

#### `azure-vm.pkr.hcl`

```hcl
build {
  name = "Linux"
  sources = ["source.azure-arm.template"]
  
  # for this don't need provisioners
}
```

### Operating system and Environment details

WSL Ubuntu 22.04

### Log Fragments and crash.log files

Error provided above

### PR DESCRIPTION
**Pull request by JenGoldstrich**
This PR adds a delete call when the force flag is set when publishing to a a Shared Image Gallery (otherwise known as a Compute Gallery)

Closes #392

### CODE REVIEW

File: builder/azure/arm/builder.go [hunk 1]
```diff
@@ -206,12 +206,22 @@ func (b *Builder) Run(ctx context.Context, ui packersdk.Ui, hook packersdk.Hook)
...
 		_, err := azureClient.GalleryImageVersionsClient.Get(ctx, galleryImageVersionId, galleryimageversions.DefaultGetOperationOptions())
 		if err == nil {
-			return nil, fmt.Errorf("a gallery image version for image name:version %s:%s already exists in gallery %s", b.config.SharedGalleryDestination.SigDestinationImageName, b.config.SharedGalleryDestination.SigDestinationImageVersion, b.config.SharedGalleryDestination.SigDestinationGalleryName)
+			if b.config.PackerForce {
+				ui.Say(fmt.Sprintf("a gallery image version for image name:version %s:%s already exists in gallery %s, but deleting it due to -force flag", b.config.SharedGalleryDestination.SigDestinationGalleryName, b.config.SharedGalleryDestination.SigDestinationImageVersion, b.config.SharedGalleryDestination.SigDestinationImageName))
+				deleteImageContext, cancel := context.WithTimeout(ctx, azureClient.PollingDuration)
+				defer cancel()
```
Comment (lbajolet-hashicorp) [inline builder/azure/arm/builder.go:216]: Why the `defer cancel`? I'm not sure I understand the rationale behind this one, if we quit the `Run` function at that point the context is either expired because it was already cancelled, or the build has finished and it will be ignored then since there's nothing left to cancel. Unless the function does something else and I'm missing something?

File: builder/azure/arm/builder.go [hunk 2]
```diff
@@ -206,12 +206,22 @@ func (b *Builder) Run(ctx context.Context, ui packersdk.Ui, hook packersdk.Hook)
...
+				err := azureClient.GalleryImageVersionsClient.DeleteThenPoll(deleteImageContext, galleryImageVersionId)
+				if err != nil {
+					return nil, fmt.Errorf("failed to delete gallery image version for image name:version %s:%s in gallery %s", b.config.SharedGalleryDestination.SigDestinationImageName, b.config.SharedGalleryDestination.SigDestinationImageVersion, b.config.SharedGalleryDestination.SigDestinationGalleryName)
+				}
+
+			} else {
+				return nil, fmt.Errorf("a gallery image version for image name:version %s:%s already exists in gallery %s, use the -force option to automatically delete it.", b.config.SharedGalleryDestination.SigDestinationImageName, b.config.SharedGalleryDestination.SigDestinationImageVersion, b.config.SharedGalleryDestination.SigDestinationGalleryName)
```
Comment (lbajolet-hashicorp) [inline builder/azure/arm/builder.go:223]: Not sure we should advocate running a build with `-force` in this error message? I worry users will see this and wipe an image without thinking too much if we encourage its use.
In general I would suggest renaming the output image (or whatever is adapted for Azure, I'll let you be the judge on that :smile:) instead of forcefully wiping, if we want to recommend an action here.

**Review by lbajolet-hashicorp — COMMENTED** [review]
Overall LGTM, I left a couple questions on the code, but when we've addressed them we can move forward with this I believe!

File: builder/azure/arm/builder.go (hunk 2 above)
Comment (JenGoldstrich) [reply builder/azure/arm/builder.go:223]: @lbajolet-hashicorp I did this because of the managed image block also using this same warning, but I am open to not showing it, if so we should remove it from both errors though.

File: builder/azure/arm/builder.go (hunk 1 above)
Comment (JenGoldstrich) [reply builder/azure/arm/builder.go:216]: It's just communicating to the SDK to stop accepting new requests from that context 🤷 I think its just best practice to cancel TimeOut contexts you create

File: builder/azure/arm/builder.go (hunk 2 above)
Comment (lbajolet-hashicorp) [reply builder/azure/arm/builder.go:223]: Fair then yeah, no objection for either if there's a precedent about `-force`, no need to change that here, or agreed for consistency we can change both. I'll let you do what you think's for the best in that case

File: builder/azure/arm/builder.go (hunk 1 above)
Comment (lbajolet-hashicorp) [reply builder/azure/arm/builder.go:216]: Could be best practice yes, no objection to do it then, but if that's systematic for the `Run` function, I'd think it can be done once when the function starts executing, and we don't need to repeat that deferred call around the various paths of the code?

**Review by lbajolet-hashicorp — APPROVED** [review]

File: builder/azure/arm/builder.go (hunk 1 above)
Comment (JenGoldstrich) [reply builder/azure/arm/builder.go:216]: We talked about this privately but just to post here for anyones context reading in the future, but there was some confusion, the cancel function isn't global and is returned by the With Context function, closing this since we talked about it

File: builder/azure/arm/builder.go (hunk 2 above)
Comment (JenGoldstrich) [reply builder/azure/arm/builder.go:223]: I will add that https://github.com/hashicorp/packer-plugin-googlecompute/blob/289eb5985bbfefc37b03743d6a6d0a8b557643c8/builder/googlecompute/step_check_existing_image.go#L28-L29 the GCP plugin also has a similar error, I think it'll be good to change this reword message on Azure though to indicate its an option rather than a definitive way to solve the problem from "use the -force option to automatically delete it." to "change the image version/image name (depending on managed image/SIG or use the -force option to automatically delete it.", I'll make that change, thanks for the suggestion!

Comment (lbajolet-hashicorp) [reply builder/azure/arm/builder.go]: Good call-out for the GCE plugin, will reword that one!
